# Generated by Django 5.2.13 on 2026-04-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='listing_type',
            field=models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio')], default='service', max_length=20),
        ),
    ]
