# Generated by Django 5.2.13 on 2026-04-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
