# Generated by Django 5.2.13 on 2026-05-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_listingtype_alter_service_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
