# Generated by Django 5.2.11 on 2026-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cilindrada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='kilometros',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
