# Generated by Django 5.2.11 on 2026-05-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_is_deleted'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviewreport',
            name='unique_review_reporter',
        ),
    ]
